# docker-compose.yml
version: '3.8'

services:
  api:
    build: ./apps/api
    ports: ["3000:3000"]
    container_name: bootcamp-api
    restart: always

  web:
    build: ./apps/web
    ports: ["8080:80"]
    environment:
      # O Front-End acessa a API usando o nome do servi√ßo 'api'
      - VITE_API_URL=http://api:3000 
    depends_on: [api]
    container_name: bootcamp-web
    restart: always
    